// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"fr": &dictionary{index: frIndex, data: frData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%dD": 6,
	"%dH": 5,
	":tada: Congratulation :tada:   No merge request to validate today :parrot:": 0,
	"Assigned":                            4,
	"MERGE REQUESTS WAITING FOR APPROVAL": 8,
	"Nobody... :sad:":                     7,
	"Project":                             1,
	"Since":                               3,
	"Title":                               2,
}

var enIndex = []uint32{ // 10 elements
	0x00000000, 0x0000004b, 0x00000053, 0x00000059,
	0x0000005f, 0x00000068, 0x0000006f, 0x00000076,
	0x00000086, 0x000000aa,
} // Size: 64 bytes

const enData string = "" + // Size: 170 bytes
	"\x02:tada: Congratulation :tada:   No merge request to validate today :p" +
	"arrot:\x02Project\x02Title\x02Since\x02Assigned\x02%[1]dH\x02%[1]dD\x02N" +
	"obody... :sad:\x02MERGE REQUESTS WAITING FOR APPROVAL"

var frIndex = []uint32{ // 10 elements
	0x00000000, 0x00000054, 0x0000005b, 0x00000061,
	0x00000068, 0x00000074, 0x0000007b, 0x00000082,
	0x00000094, 0x000000ae,
} // Size: 64 bytes

const frData string = "" + // Size: 174 bytes
	"\x02:tada: Félicitations :tada:   Aucune merge request à valider aujourd" +
	"'hui :parrot:\x02Projet\x02Titre\x02Depuis\x02Assigné à\x02%[1]dH\x02%[1" +
	"]dJ\x02Personne... :sad:\x02MERGE REQUESTS À VALIDER"

	// Total table size 472 bytes (0KiB); checksum: 863F41D8
